//Promises
//Real Life Ex...--> Either Fullfilled or Rejected...
//We Used Promises Bcz Avoiding CallBack Hell...
myPromise.then(
    function(value) { /* code if successful */ },
    function(error) { /* code if some error (Server Error...etc...system error...)*/  }
  );
//BUT We Used Mostly Async Wait...
